services:
  db:
    image: postgres:latest
    container_name: soccerlab_db
    restart: always
    env_file: ./backend/.dev.env
    networks:
      - internal
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: soccerlab_backend
    env_file: ./backend/.dev.env
    networks:
      - web
      - internal
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: soccerlab_frontend
    networks:
      - web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
networks:
  web:
    driver: bridge
  internal:
    driver: bridge
    internal: true
    # internal 네트워크는 외부에서 접근할 수 없음
