# 1. 프론트 서버 빌드결과물만 포함할 경량 이미지
FROM nginx:alpine

# 2. 빌드된 정적 파일을 Nginx 정적 루트로 복사
COPY --from=builder /app/dist /usr/share/nginx/html

# 3. Nginx 설정 덮어쓰기 (불필요. yml 파일에서 nginx.conf를 볼륨마운트로 연결)
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# 4. 포트 노출
EXPOSE 80

# # 5. 기본 명령 (이미지 실행 시 Nginx 자동 실행)
# # CMD를 사용하지 않아도 Nginx가 기본적으로 nginx.conf를 읽어들이고 nginx -g daemon off;를 실행한다.
# CMD ["nginx", "-g", "daemon off;"]
